### ISSUE TITLE
Handler not executed in multiple steps chain between different environment

### ISSUE THREAD

**Issue by Rastopyr** [edjafarov/PromisePipe#24]
```javascript
function logInPipe(data, context) {
  console.log('inPipe', data);
  return data;
}

var readDirectory = PromisePipe()
  .then(onServer(readDir))
  .then(logInPipe) // not executed
  .then(onServer(logInPipe)); // executed
```

**Comment by edjafarov** [comment]
I will debug deeper but it looks like https://github.com/edjafarov/PromisePipe/blob/master/src/PromisePipe.js#L415 is not working properly while getting last chain inside nested piece

**Comment by edjafarov** [comment]
It is really strange, but it works in tests. I will try to reproduce it on example.

**Comment by edjafarov** [comment]
It is reproduced on example:) it is false positive in tests, nice catch:)

**Comment by edjafarov** [comment]
fixed
